version: '3.8'

services:
  mechanical-assistant:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: mechanical-assistant:latest
    container_name: mechanical-assistant-app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/models:/app/models
      - ./backend/index:/app/index
      - ./backend/CMAPSSData:/app/CMAPSSData
    restart: always
